# Generated by Django 5.1.4 on 2025-01-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_studentexcelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='grade',
            field=models.FloatField(),
        ),
    ]
