# Generated by Django 5.1.4 on 2024-12-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_image', models.ImageField(upload_to='homepage/')),
                ('welcome_text', models.TextField(default='خوش آمدید به سیستم مدیریت مدرسه هوشمند اما علی(ع)')),
            ],
        ),
    ]
